In [4]:
#Imports:
import pandas as pd
import numpy as np
from numpy import delete
import scipy.stats as stats

#Código necesario para correr funciones desde otro archivo .ipynb de la misma carpeta
%run Preparar_datos.ipynb
%run TablaResumenCC.ipynb

# Índice: Qué hay en este fichero

 ¿Las oscilaciones diarias se deben a un intercambio de aire con el exterior?
- CCs sin suavizar datos de (Th-Te)_CO2h, (Tc_Te)_CO2c, (Tp-Te)_CO2p
- CCs tras suavizar datos de (Th-Te)_CO2h, (Tc_Te)_CO2c, (Tp-Te)_CO2p


Significado de las abreviaturas:
- CC: Coeficientes de correlación
- CO2h: Partes por millón de CO2 en el aire de Hall
- CO2c: Partes por millón de CO2 en el aire de Cruce
- CO2p: Partes por millón de CO2 en el aire de Policromos

Solo obtener para los mese con oscilaciones claras:
- 1) Los meses con oscilaciones claras para el C02 del cruce son: 
 Julio, agosto y septiembre de 2021.
 Junio, julio, agosto y septiembre de 2022
- 2) Los meses con oscilaciones claras para el CO2 del hall son:
Julio, agosto, septiembre y octubre de 2021. Mayo, junio y julio de 2022

# 4.1) ¿Las oscilaciones diarias se deben a un intercambio de aire con el exterior? Coeficientes de correlación entre la diferencia de temperaturas entre exterior y cada sala con la cantidad de CO2. Variables sin suavizar

### Preparar datos:

Unir los meses de cada año en un solo df:

In [2]:
###Entrada:
#Leer los datos
#2021
dfEntrada_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA ENTRADA A.xlsx")
dfEntrada_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA ENTRADA A.xlsx")
dfEntrada_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA ENTRADA A.xlsx")
dfEntrada_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA ENTRADA A.xlsx")
#2022
dfEntrada_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA ENTRADA A.xlsx")
dfEntrada_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA ENTRADA A.xlsx")
dfEntrada_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA ENTRADA A.xlsx")
#Unir df:
dfEntrada_21 = pd.concat([dfEntrada_7_21, dfEntrada_8_21, dfEntrada_9_21, dfEntrada_10_21], axis=0)
dfEntrada_22 = pd.concat([dfEntrada_7_22, dfEntrada_8_22, dfEntrada_9_22], axis=0)

###Cruce:
#Leer los datos
#2021
dfCruce_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA CRUCE D.xlsx")
dfCruce_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA CRUCE D.xlsx")
dfCruce_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA CRUCE D.xlsx")
dfCruce_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA CRUCE D.xlsx")
#2022
dfCruce_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA CRUCE C.xlsx")
dfCruce_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA CRUCE D.xlsx")
dfCruce_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA CRUCE D.xlsx")
#Unir df:
dfCruce_21 = pd.concat([dfCruce_7_21, dfCruce_8_21, dfCruce_9_21, dfCruce_10_21], axis=0)
dfCruce_22 = pd.concat([dfCruce_7_22, dfCruce_8_22, dfCruce_9_22], axis=0)

###Exterior:
#Leer los datos
#2021
dfExterior_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA EXTERIOR.xlsx")
dfExterior_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA EXTERIOR.xlsx")
dfExterior_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA EXTERIOR.xlsx")
dfExterior_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA EXTERIOR.xlsx")
#2022
dfExterior_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA EXTERIOR.xlsx")
dfExterior_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA EXTERIOR.xlsx")
dfExterior_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA EXTERIOR.xlsx")
#Unir df:
dfExterior_21 = pd.concat([dfExterior_7_21, dfExterior_8_21, dfExterior_9_21, dfExterior_10_21], axis=0)
dfExterior_22 = pd.concat([dfExterior_7_22, dfExterior_8_22, dfExterior_9_22], axis=0)

###Policromos:
#Leer los datos
#2021
dfPolicromos_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA POLICROMOS C.xlsx")
dfPolicromos_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA POLICROMOS C.xlsx")
dfPolicromos_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA POLICROMOS C.xlsx")
dfPolicromos_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA POLICROMOS.xlsx")
#2022
dfPolicromos_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA POLICROMOS C.xlsx")
dfPolicromos_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA POLICROMOS C.xlsx")
dfPolicromos_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA POLICROMOS C.xlsx")
#Unir df:
dfPolicromos_21 = pd.concat([dfPolicromos_7_21, dfPolicromos_8_21, dfPolicromos_9_21, dfPolicromos_10_21], axis=0)
dfPolicromos_22 = pd.concat([dfPolicromos_7_22, dfPolicromos_8_22, dfPolicromos_9_22], axis=0)

In [3]:
#Resetear los índices de los df:
dfPolicromos_21= dfPolicromos_21.reset_index(drop=True)
dfPolicromos_22= dfPolicromos_22.reset_index(drop=True)
dfExterior_21= dfExterior_21.reset_index(drop=True)
dfExterior_22= dfExterior_22.reset_index(drop=True)
dfCruce_21= dfCruce_21.reset_index(drop=True)
dfCruce_22= dfCruce_22.reset_index(drop=True)
dfEntrada_21= dfEntrada_21.reset_index(drop=True)
dfEntrada_22= dfEntrada_22.reset_index(drop=True)

In [4]:
#Guardar df  en archivos excel:
dfCruce_21.to_excel('./DatosDeInteresPorSalasYAños/Cruce21.xlsx')
dfCruce_22.to_excel('./DatosDeInteresPorSalasYAños/Cruce22.xlsx')
dfExterior_21.to_excel('./DatosDeInteresPorSalasYAños/Exterior21.xlsx')
dfExterior_22.to_excel('./DatosDeInteresPorSalasYAños/Exterior22.xlsx')
dfEntrada_21.to_excel('./DatosDeInteresPorSalasYAños/Hall21.xlsx')
dfEntrada_22.to_excel('./DatosDeInteresPorSalasYAños/Hall22.xlsx')
dfPolicromos_21.to_excel('./DatosDeInteresPorSalasYAños/Policromos21.xlsx')
dfPolicromos_22.to_excel('./DatosDeInteresPorSalasYAños/Policromos22.xlsx')

In [5]:
# Datos cada 15 mins Policromos de los archivos unidos:
DatosPolicromos_21 = adaptar_len_policromos('./DatosDeInteresPorSalasYAños/Cruce21.xlsx',
                                            './DatosDeInteresPorSalasYAños/Exterior21.xlsx',
                                            './DatosDeInteresPorSalasYAños/Hall21.xlsx',
                                            './DatosDeInteresPorSalasYAños/Policromos21.xlsx','2021')
DatosPolicromos_22 = adaptar_len_policromos('./DatosDeInteresPorSalasYAños/Cruce22.xlsx',
                                            './DatosDeInteresPorSalasYAños/Exterior22.xlsx',
                                            './DatosDeInteresPorSalasYAños/Hall22.xlsx',
                                            './DatosDeInteresPorSalasYAños/Policromos22.xlsx', '2022')

In [6]:
#Separar por semanas:
SemanaCruce21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Cruce21.xlsx')
SemanaCruce22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Cruce22.xlsx')
SemanaExterior21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Exterior21.xlsx')
SemanaExterior22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Exterior22.xlsx')
SemanaHall21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Hall21.xlsx')
SemanaHall22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Hall22.xlsx')
PolicromosSemanas_2021 = separar_policromos_semanas(DatosPolicromos_21)
PolicromosSemanas_2022 = separar_policromos_semanas(DatosPolicromos_22)

### Comprobaciones datos semanas:

In [7]:
print(len(SemanaCruce21), len(SemanaExterior21),len(SemanaHall21), len(PolicromosSemanas_2021))

18 18 18 18


In [8]:
print(len(SemanaCruce22), len(SemanaExterior22),len(SemanaHall22), len(PolicromosSemanas_2022))

14 14 14 14


In [9]:
#2021:
print('¿Número de datos iguales para el 21?')
i=0
while i<18:
    print(len(SemanaCruce21[i]), len(SemanaExterior21[i]), len(SemanaHall21[i]), len(PolicromosSemanas_2021[i]))
    i=i+1

#2022:
print('¿Número de datos iguales para el 22?')
i=0
while i<14:
    print(len(SemanaCruce22[i]), len(SemanaExterior22[i]), len(SemanaHall22[i]), len(PolicromosSemanas_2022[i]))
    i=i+1

¿Número de datos iguales para el 21?
384 384 384 384
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
339 339 339 672
480 480 480 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
¿Número de datos iguales para el 22?
286 287 286 288
672 672 672 672
672 672 672 672
672 672 672 672
670 669 670 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
480 480 480 480


In [12]:
# #Pintar mes en caso de problemas:
# i=0
# while i<672:
#     print(SemanaCruce22[0]['Fecha/Tiempo'][i], SemanaExterior22[0]['Fecha/Tiempo'][i],SemanaHall22[0]['Fecha/Tiempo'][i],
#           PolicromosSemanas_2022[0]['Fecha/Tiempo'][i])
#     i=i+1

### Problemas en los ficheros:
- A Semana 8 (contando desde 0) de 2021 le faltan datos al final en Cruce, Hall y Entrada, recortar Policromos a la longitud de los demas, 339 datos.
- Semana 9 de 2021: Faltan los datos de los dos primeros días de Cruce, Hall y Entrada. Cortar los 24*60/16=192 primeros datos de Policromos.
- Semana 0 de 2022: Policromos empieza 2 datos antes, los otros terminan dos datos después. Cortar 2 datos de policromos al inicio. Cortar los datos en <286-2 al final.
- Semana 4 de 2022: Exterior es más corto, igualar la longitud de los otros 3 archivos a la de exterior, 669 datos
- Semana 13 de 2022: Policromos más largo, cortar en 480

In [13]:
##Arreglar los problemas en los datos por semanas:
#Semana 8 de 2021:
PolicromosSemanas_2021[8]=PolicromosSemanas_2021[8][:339]
#Semana 8 de 2021:
PolicromosSemanas_2021[9]=PolicromosSemanas_2021[9][192:]
PolicromosSemanas_2021[9]=PolicromosSemanas_2021[9].reset_index(drop=True)
#Semana 0 de 2022:
PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0][2:]
PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0].reset_index(drop=True)
PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0][:286]
SemanaExterior22[0]=SemanaExterior22[0][:286]
#Semana 4 de 2022:
SemanaHall22[4]=SemanaHall22[4][:669]
SemanaCruce22[4]=SemanaCruce22[4][:669]
PolicromosSemanas_2022[4]=PolicromosSemanas_2022[4][:669]
#Semana 13 de 2022:
PolicromosSemanas_2022[13]=PolicromosSemanas_2022[13][:480]

In [14]:
#Comprobar que se han solucionado los problemas:
#2021:
print('¿Número de datos iguales para el 21?')
i=0
while i<18:
    print(len(SemanaCruce21[i]), len(SemanaExterior21[i]), len(SemanaHall21[i]), len(PolicromosSemanas_2021[i]))
    i=i+1

#2022:
print('¿Número de datos iguales para el 22?')
i=0
while i<14:
    print(len(SemanaCruce22[i]), len(SemanaExterior22[i]), len(SemanaHall22[i]), len(PolicromosSemanas_2022[i]))
    i=i+1

¿Número de datos iguales para el 21?
384 384 384 384
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
339 339 339 339
480 480 480 480
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
¿Número de datos iguales para el 22?
286 286 286 286
672 672 672 672
672 672 672 672
672 672 672 672
669 669 669 669
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
672 672 672 672
480 480 480 480


### Obtener coeficientes:

In [22]:
#Función adaptada a datos sin suavizar
def difT_CO2_cc_por_semanas(DataframeCruce, DataframeExterior, DataframeHall, PolicromosSemanas):
    """
    Atributos:
    1) DataframeCruce: Lista de dataframes por semanas correspondiente a los datos de un mes de Cruce
    2) DataframeExterior: Lista de dataframes por semanas correspondiente a los datos de un mes de Exterior
    3) DataframeHall: Lista de dataframes por semanas correspondiente a los datos de un mes de Hall
    4) DatosPolicromos: Lista de dataframes por semanas correspondiente a los datos de un mes de Policromos
    
    Devuelve:
    Una lista de listas, r. Cada elemento de r, r[i] con i=0, 1, 2, 3, 4, es una lista con los coeficiente de correlación y p 
    valores correspondientes a una semana.  r[i] = r_difT_CO2_cruce, p_difT_CO2_cruce, r_difT_CO2_hall, p_difT_CO2_hall, 
                                                   r_difT_CO2_policromos, p_difT_CO2_policromos
    
    ¿A qué corresponde cada elemento de r[i]?
    1) r_difT_CO2_cruce: Coeficiente de correlación entre la diferencia de temperaturas de Cruce y el exterior y el CO2 del 
    Cruce
    2) p_difT_CO2_cruce: P-valor correspondiente a r_difT_CO2_cruce
    3) r_difT_CO2_hall: Coeficiente de correlación entre la diferencia de temperaturas de Cruce y el exterior y el CO2 del Hall
    4) p_difT_CO2_hall: P-valor correspondiente a r_difT_CO2_hall
    5) r_difT_CO2_policromos: Coeficiente de correlación entre la diferencia de temperaturas de Cruce y el exterior y el CO2 de 
    Policromos
    6) p_difT_CO2_policromos: P-valor correspondiente a r_Tp_Te
    """
    i=0
    r=[]
    while i<len(DataframeCruce):
       #print(i)
        DataframeCruce[i].reset_index(drop=True, inplace=True)
        DataframeExterior[i].reset_index(drop=True, inplace=True)
        DataframeHall[i].reset_index(drop=True, inplace=True)
        PolicromosSemanas[i].reset_index(drop=True, inplace=True)
        
        # Variables que me van a hacer falta: Tc, Te, Th, Tp, CO2c, CO2h, CO2p
        for index, _ in DataframeExterior[i].iterrows():#Se va fuera de indice
            if  __builtins__.sum([pd.isna(DataframeCruce[i]["Temperatura D (° C)"][index]),
                                  pd.isna(DataframeCruce[i]['CO2 D (ppm)'][index]),
                                  pd.isna(DataframeHall[i]['Temperatura A (° C)'][index]),
                                  pd.isna(DataframeHall[i]['CO2 A (ppm)'][index]),
                                  pd.isna(PolicromosSemanas[i]['Tp'][index]),
                                  pd.isna(PolicromosSemanas[i]["CO2"][index]),
                                  pd.isna(DataframeExterior[i]["Tr Exterior (C Tr)"][index])]) > 0:
                DataframeCruce[i].drop([index], axis=0, inplace=True)
                DataframeExterior[i].drop([index], axis=0, inplace=True) 
                DataframeHall[i].drop([index], axis=0, inplace=True) 
                PolicromosSemanas[i].drop([index], axis=0, inplace=True) 
                
        #Quiero los coef entre CO2 y dif de temperaturas:
        Dif_T_cruce= DataframeExterior[i]["Tr Exterior (C Tr)"]-DataframeCruce[i]["Temperatura D (° C)"]
        Dif_T_Hall = DataframeExterior[i]["Tr Exterior (C Tr)"]-DataframeHall[i]['Temperatura A (° C)']
        Dif_T_Policromos = DataframeExterior[i]["Tr Exterior (C Tr)"]-PolicromosSemanas[i]['Tp']
        #Mediante scipy:
        r_difT_CO2_cruce, p_difT_CO2_cruce = stats.pearsonr(Dif_T_cruce, DataframeCruce[i]["CO2 D (ppm)"])
        r_difT_CO2_hall, p_difT_CO2_hall = stats.pearsonr(Dif_T_Hall, DataframeHall[i]["CO2 A (ppm)"])
        r_difT_CO2_policromos, p_difT_CO2_policromos = stats.pearsonr(Dif_T_Policromos, PolicromosSemanas[i]["CO2"])
        rs = r_difT_CO2_cruce, p_difT_CO2_cruce, r_difT_CO2_hall, p_difT_CO2_hall, r_difT_CO2_policromos, p_difT_CO2_policromos, len(DataframeExterior[i]["Tr Exterior (C Tr)"])
#         rs = r_difT_CO2_cruce, p_difT_CO2_cruce, r_difT_CO2_hall, p_difT_CO2_hall, len(DataframeExterior[i]["Tr Exterior (C Tr)"])
        r.append(rs)
        i=i+1
    return(r)

In [23]:
cc21 = difT_CO2_cc_por_semanas(SemanaCruce21, SemanaExterior21, SemanaHall21, PolicromosSemanas_2021)
cc22 = difT_CO2_cc_por_semanas(SemanaCruce22, SemanaExterior22, SemanaHall22, PolicromosSemanas_2022)

In [25]:
s1=pd.Series([cc21[0][0], cc21[1][0],cc21[2][0],cc21[3][0],cc21[4][0],cc21[5][0],cc21[6][0],cc21[7][0],cc21[8][0],cc21[9][0],
              cc21[10][0], cc21[11][0], cc21[12][0], cc21[13][0], cc21[14][0], cc21[15][0], cc21[16][0], cc21[17][0], 
              cc22[0][0], cc22[1][0],cc22[2][0],cc22[3][0],cc22[4][0],cc22[5][0],cc22[6][0],cc22[7][0],cc21[8][0],
              cc22[9][0], cc22[10][0], cc22[11][0], cc22[12][0], cc22[13][0]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s2=pd.Series([cc21[0][1], cc21[1][1],cc21[2][1],cc21[3][1],cc21[4][1],cc21[5][1],cc21[6][1],cc21[7][1],cc21[8][1],cc21[9][1],
              cc21[10][1], cc21[11][1], cc21[12][1], cc21[13][1], cc21[14][1], cc21[15][1], cc21[16][1], cc21[17][1], 
              cc22[0][1], cc22[1][1],cc22[2][1],cc22[3][1],cc22[4][1],cc22[5][1],cc22[6][1],cc22[7][1],cc21[8][1],
              cc22[9][1], cc22[10][1], cc22[11][1], cc22[12][1], cc22[13][1]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s3=pd.Series([cc21[0][2], cc21[1][2],cc21[2][2],cc21[3][2],cc21[4][2],cc21[5][2],cc21[6][2],cc21[7][2],cc21[8][2],cc21[9][2],
              cc21[10][2], cc21[11][2], cc21[12][2], cc21[13][2], cc21[14][2], cc21[15][2], cc21[16][2], cc21[17][2], 
              cc22[0][2], cc22[1][2],cc22[2][2],cc22[3][2],cc22[4][2],cc22[5][2],cc22[6][2],cc22[7][2],cc21[8][2],
              cc22[9][2], cc22[10][2], cc22[11][2], cc22[12][2], cc22[13][2]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s4=pd.Series([cc21[0][3], cc21[1][3],cc21[2][3],cc21[3][3],cc21[4][3],cc21[5][3],cc21[6][3],cc21[7][3],cc21[8][3],cc21[9][3],
              cc21[10][3], cc21[11][3], cc21[12][3], cc21[13][3], cc21[14][3], cc21[15][3], cc21[16][3], cc21[17][3], 
              cc22[0][3], cc22[1][3],cc22[2][3],cc22[3][3],cc22[4][3],cc22[5][3],cc22[6][3],cc22[7][3],cc21[8][3],
              cc22[9][3], cc22[10][3], cc22[11][3], cc22[12][3], cc22[13][3]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s5=pd.Series([cc21[0][4], cc21[1][4],cc21[2][4],cc21[3][4],cc21[4][4],cc21[5][4],cc21[6][4],cc21[7][4],cc21[8][4],cc21[9][4],
              cc21[10][4], cc21[11][4], cc21[12][4], cc21[13][4], cc21[14][4], cc21[15][4], cc21[16][4], cc21[17][4], 
              cc22[0][4], cc22[1][4],cc22[2][4],cc22[3][4],cc22[4][4],cc22[5][4],cc22[6][4],cc22[7][4],cc21[8][4],
              cc22[9][4], cc22[10][4], cc22[11][4], cc22[12][4], cc22[13][4]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s6=pd.Series([cc21[0][5], cc21[1][5],cc21[2][5],cc21[3][5],cc21[4][5],cc21[5][5],cc21[6][5],cc21[7][5],cc21[8][5],cc21[9][5],
              cc21[10][5], cc21[11][5], cc21[12][5], cc21[13][5], cc21[14][5], cc21[15][5], cc21[16][5], cc21[17][5], 
              cc22[0][5], cc22[1][5],cc22[2][5],cc22[3][5],cc22[4][5],cc22[5][5],cc22[6][5],cc22[7][5],cc21[8][5],
              cc22[9][5], cc22[10][5], cc22[11][5], cc22[12][5], cc22[13][5]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s7=pd.Series([cc21[0][6], cc21[1][6],cc21[2][6],cc21[3][6],cc21[4][6],cc21[5][6],cc21[6][6],cc21[7][6],cc21[8][6],cc21[9][6],
              cc21[10][6], cc21[11][6], cc21[12][6], cc21[13][6], cc21[14][6], cc21[15][6], cc21[16][6], cc21[17][6], 
              cc22[0][6], cc22[1][6],cc22[2][6],cc22[3][6],cc22[4][6],cc22[5][6],cc22[6][6],cc22[7][6],cc21[8][6],
              cc22[9][6], cc22[10][6], cc22[11][6], cc22[12][6], cc22[13][6]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
#unir en dataframe
CoefCorrel = pd.concat([s1, s2, s3, s4, s5, s6, s7], axis = 1)
CoefCorrel.columns = ['CC_difT_CO2_cruce', 'pvalue_difT_CO2_cruce', 'CC_difT_CO2_hall',  'pvalue_hall', 
                      'CC_difT_CO2_policromos',  'pvalue_polimos', 'nº datos']
display(CoefCorrel)
CoefCorrel.describe()

CC_difT_CO2_cruce  pvalue_difT_CO2_cruce  CC_difT_CO2_hall  \
Sem0 2021           -0.666723           1.039730e-50         -0.386983   
Sem1 2021           -0.670508           8.392440e-89         -0.461425   
Sem2 2021           -0.647755           3.376392e-81         -0.326137   
Sem3 2021           -0.550807           1.406587e-54         -0.125804   
Sem4 2021           -0.669074           2.002801e-88         -0.493621   
Sem5 2021           -0.635469           2.728410e-77         -0.278907   
Sem6 2021           -0.693486           2.467955e-97         -0.158082   
Sem7 2021           -0.603726           5.675587e-68         -0.132187   
Sem8 2021           -0.569650           1.304487e-29         -0.212867   
Sem9 2021           -0.817806           1.060388e-06         -0.658658   
Sem10 2021          -0.397770           1.233636e-26          0.585893   
Sem11 2021          -0.534526           7.568261e-51         -0.128429   
Sem12 2021          -0.582382           4.297506e-62         -0.473609   
Sem13 2021          -0.305030           6.477015e-16         -0.285875   
Sem14 2021          -0.256886           1.374095e-11         -0.198972   
Sem15 2021          -0.508776           1.578850e-45         -0.520126   
Sem0162021          -0.640609           6.653393e-79         -0.781431   
Sem17 2021          -0.516711           3.849899e-47         -0.486662   
Sem0 2022           -0.499055           2.035168e-19         -0.478597   
Sem1 2022           -0.508597           1.715103e-45         -0.171376   
Sem2 2022           -0.499774           9.490829e-44          0.283901   
Sem3 2022           -0.396017           1.172930e-26         -0.206016   
Sem4 2022           -0.476891           2.737136e-39         -0.387606   
Sem5 2022           -0.198780           2.043815e-07          0.114061   
Sem6 2022           -0.353616           1.023971e-08          0.423979   
Sem7 2022           -0.481734           1.799112e-30         -0.473839   
Sem8 2021           -0.569650           1.304487e-29         -0.212867   
Sem9 2022           -0.517587           2.539830e-47          0.142469   
Sem10 2022          -0.353872           2.956269e-21          0.262055   
Sem11 2022          -0.414335           2.923574e-29         -0.017721   
Sem12 2022          -0.384819           8.341447e-22         -0.435779   
Sem13 2022          -0.442850           1.791836e-24         -0.613525   

              pvalue_hall  CC_difT_CO2_policromos  pvalue_polimos  nº datos  
Sem0 2021    3.626907e-15               -0.382689    7.693070e-15       384  
Sem1 2021    1.102193e-36               -0.106301    5.846332e-03       671  
Sem2 2021    4.061759e-18               -0.009628    8.032563e-01       672  
Sem3 2021    1.082580e-03                0.332825    7.599153e-19       672  
Sem4 2021    1.456391e-42               -0.229014    1.905614e-09       672  
Sem5 2021    1.794923e-13                0.132164    5.930139e-04       672  
Sem6 2021    3.902851e-05               -0.160570    2.931300e-05       671  
Sem7 2021    5.916957e-04                0.227621    2.399872e-09       672  
Sem8 2021    1.022928e-04                0.351847    5.424144e-11       328  
Sem9 2021    4.659455e-04                0.788224    4.786086e-06        24  
Sem10 2021   1.533417e-62                0.339215    2.272344e-19       665  
Sem11 2021   8.548767e-04               -0.086953    2.429318e-02       671  
Sem12 2021   9.297532e-39               -0.075065    5.212385e-02       670  
Sem13 2021   4.368659e-14                0.235496    6.578541e-10       671  
Sem14 2021   1.988356e-07                0.127747    9.033567e-04       672  
Sem15 2021   7.553552e-48                0.041312    2.848935e-01       672  
Sem0162021  2.317617e-139               -0.171333    7.960166e-06       672  
Sem17 2021   2.990365e-41                0.116061    2.584816e-03       672  
Sem0 2022    8.856146e-18               -0.012956    8.273042e-01       286  
Sem1 2022

CC_difT_CO2_cruce  pvalue_difT_CO2_cruce  CC_difT_CO2_hall  \
count          32.000000           3.200000e+01         32.000000   
mean           -0.511415           3.984448e-08         -0.227961   
std             0.137732           1.896939e-07          0.318175   
min            -0.817806           2.467955e-97         -0.781431   
25%            -0.611661           1.054941e-54         -0.473667   
50%            -0.512744           1.368615e-39         -0.245887   
75%            -0.410193           2.098801e-22         -0.127772   
max            -0.198780           1.060388e-06          0.585893   

         pvalue_hall  CC_difT_CO2_policromos  pvalue_polimos    nº datos  
count   3.200000e+01               32.000000    3.200000e+01   32.000000  
mean    2.040842e-02                0.090511    6.432066e-02  581.125000  
std     1.142583e-01                0.262815    2.034629e-01  168.410357  
min    2.317617e-139               -0.382689    7.939700e-21   24.000000  
25%     1.572589e-29               -0.110813    3.767155e-13  558.000000  
50%     1.214783e-13                0.113698    3.142092e-06  671.500000  
75%     1.022928e-04                0.291386    5.978494e-03  672.000000  
max     6.465447e-01                0.788224    8.273042e-01  672.000000

### ¿Cuántos coeficientes caen en cada intervalo de valores?

In [26]:
ordenar_valores_cc (CoefCorrel, 'CC_difT_CO2_cruce', 'pvalue_difT_CO2_cruce', 'CC_difT_CO2_hall',  'pvalue_hall', 
                      'CC_difT_CO2_policromos',  'pvalue_polimos')

CC_difT_CO2_cruce  CC_difT_CO2_hall  CC_difT_CO2_policromos
cc>0.5                   0                 1                       2
cc>0                     0                 5                      16
cc>-0.5                 14                22                      14
cc>-1                   18                 4                       0
total                   32                32                      32

# 4.2) ¿Las oscilaciones diarias se deben a un intercambio de aire con el exterior? Coeficientes de correlación entre la diferencia de temperaturas entre exterior y cada sala con la cantidad de CO2. Variables suavizadas

### Preparar datos:

En el proceso de obtención de los coeficientes se borran datos. Es necesario volver a calcular las listas de dataframes por semanas cada vez que se quieran obtener coeficientes para evitar perder datos.

In [5]:
# ###Entrada:
# #Leer los datos
# #2021
# dfEntrada_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA ENTRADA A.xlsx")
# dfEntrada_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA ENTRADA A.xlsx")
# dfEntrada_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA ENTRADA A.xlsx")
# dfEntrada_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA ENTRADA A.xlsx")
# #2022
# dfEntrada_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA ENTRADA A.xlsx")
# dfEntrada_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA ENTRADA A.xlsx")
# dfEntrada_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA ENTRADA A.xlsx")
# #Unir df:
# dfEntrada_21 = pd.concat([dfEntrada_7_21, dfEntrada_8_21, dfEntrada_9_21, dfEntrada_10_21], axis=0)
# dfEntrada_22 = pd.concat([dfEntrada_7_22, dfEntrada_8_22, dfEntrada_9_22], axis=0)

# ###Cruce:
# #Leer los datos
# #2021
# dfCruce_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA CRUCE D.xlsx")
# dfCruce_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA CRUCE D.xlsx")
# dfCruce_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA CRUCE D.xlsx")
# dfCruce_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA CRUCE D.xlsx")
# #2022
# dfCruce_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA CRUCE C.xlsx")
# dfCruce_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA CRUCE D.xlsx")
# dfCruce_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA CRUCE D.xlsx")
# #Unir df:
# dfCruce_21 = pd.concat([dfCruce_7_21, dfCruce_8_21, dfCruce_9_21, dfCruce_10_21], axis=0)
# dfCruce_22 = pd.concat([dfCruce_7_22, dfCruce_8_22, dfCruce_9_22], axis=0)

# ###Exterior:
# #Leer los datos
# #2021
# dfExterior_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA EXTERIOR.xlsx")
# dfExterior_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA EXTERIOR.xlsx")
# dfExterior_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA EXTERIOR.xlsx")
# dfExterior_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA EXTERIOR.xlsx")
# #2022
# dfExterior_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA EXTERIOR.xlsx")
# dfExterior_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA EXTERIOR.xlsx")
# dfExterior_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA EXTERIOR.xlsx")
# #Unir df:
# dfExterior_21 = pd.concat([dfExterior_7_21, dfExterior_8_21, dfExterior_9_21, dfExterior_10_21], axis=0)
# dfExterior_22 = pd.concat([dfExterior_7_22, dfExterior_8_22, dfExterior_9_22], axis=0)

# ###Policromos:
# #Leer los datos
# #2021
# dfPolicromos_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA POLICROMOS C.xlsx")
# dfPolicromos_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA POLICROMOS.xlsx")
# #2022
# dfPolicromos_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA POLICROMOS C.xlsx")
# #Unir df:
# dfPolicromos_21 = pd.concat([dfPolicromos_7_21, dfPolicromos_8_21, dfPolicromos_9_21, dfPolicromos_10_21], axis=0)
# dfPolicromos_22 = pd.concat([dfPolicromos_7_22, dfPolicromos_8_22, dfPolicromos_9_22], axis=0)

# #Resetear los índices de los df:
# dfPolicromos_21= dfPolicromos_21.reset_index(drop=True)
# dfPolicromos_22= dfPolicromos_22.reset_index(drop=True)
# dfExterior_21= dfExterior_21.reset_index(drop=True)
# dfExterior_22= dfExterior_22.reset_index(drop=True)
# dfCruce_21= dfCruce_21.reset_index(drop=True)
# dfCruce_22= dfCruce_22.reset_index(drop=True)
# dfEntrada_21= dfEntrada_21.reset_index(drop=True)
# dfEntrada_22= dfEntrada_22.reset_index(drop=True)

# #Guardar df  en archivos excel:
# dfCruce_21.to_excel('./DatosDeInteresPorSalasYAños/Cruce21.xlsx')
# dfCruce_22.to_excel('./DatosDeInteresPorSalasYAños/Cruce22.xlsx')
# dfExterior_21.to_excel('./DatosDeInteresPorSalasYAños/Exterior21.xlsx')
# dfExterior_22.to_excel('./DatosDeInteresPorSalasYAños/Exterior22.xlsx')
# dfEntrada_21.to_excel('./DatosDeInteresPorSalasYAños/Hall21.xlsx')
# dfEntrada_22.to_excel('./DatosDeInteresPorSalasYAños/Hall22.xlsx')
# dfPolicromos_21.to_excel('./DatosDeInteresPorSalasYAños/Policromos21.xlsx')
# dfPolicromos_22.to_excel('./DatosDeInteresPorSalasYAños/Policromos22.xlsx')

# # Datos cada 15 mins Policromos de los archivos unidos:
# DatosPolicromos_21 = adaptar_len_policromos('./DatosDeInteresPorSalasYAños/Cruce21.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Exterior21.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Hall21.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Policromos21.xlsx','2021')
# DatosPolicromos_22 = adaptar_len_policromos('./DatosDeInteresPorSalasYAños/Cruce22.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Exterior22.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Hall22.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Policromos22.xlsx', '2022')
# #Separar por semanas:
# SemanaCruce21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Cruce21.xlsx')
# SemanaCruce22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Cruce22.xlsx')
# SemanaExterior21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Exterior21.xlsx')
# SemanaExterior22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Exterior22.xlsx')
# SemanaHall21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Hall21.xlsx')
# SemanaHall22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Hall22.xlsx')
# PolicromosSemanas_2021 = separar_policromos_semanas(DatosPolicromos_21)
# PolicromosSemanas_2022 = separar_policromos_semanas(DatosPolicromos_22)

# ##Arreglar los problemas en los datos por semanas:
# #Semana 8 de 2021:
# PolicromosSemanas_2021[8]=PolicromosSemanas_2021[8][:339]
# #Semana 8 de 2021:
# PolicromosSemanas_2021[9]=PolicromosSemanas_2021[9][192:]
# PolicromosSemanas_2021[9]=PolicromosSemanas_2021[9].reset_index(drop=True)
# #Semana 0 de 2022:
# PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0][2:]
# PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0].reset_index(drop=True)
# PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0][:286]
# SemanaExterior22[0]=SemanaExterior22[0][:286]
# #Semana 4 de 2022:
# SemanaHall22[4]=SemanaHall22[4][:669]
# SemanaCruce22[4]=SemanaCruce22[4][:669]
# PolicromosSemanas_2022[4]=PolicromosSemanas_2022[4][:669]
# #Semana 13 de 2022:
# PolicromosSemanas_2022[13]=PolicromosSemanas_2022[13][:480]

In [6]:
#Solo cortado y pegado, añadir longitud de datos

In [16]:
# PolicromosSemanas_2021[13]

Tp  Tp_suavizada     CO2  CO2_suavizado            Fecha/Tiempo  week
0    14.56        14.556  1113.0         1114.8 2021-09-27 00:05:55.090    39
1    14.57        14.562  1102.0         1116.6 2021-09-27 00:20:55.090    39
2    14.56        14.562  1120.0         1115.2 2021-09-27 00:35:55.090    39
3    14.56        14.562  1109.0         1112.2 2021-09-27 00:50:55.090    39
4    14.57        14.570  1127.0         1116.6 2021-09-27 01:05:55.090    39
..     ...           ...     ...            ...                     ...   ...
667  14.59        14.594  1813.0         1809.2 2021-10-03 22:50:55.090    39
668  14.59        14.594  1809.0         1814.0 2021-10-03 23:05:55.090    39
669  14.59        14.590  1825.0         1819.6 2021-10-03 23:20:55.090    39
670  14.58        14.590  1820.0         1821.0 2021-10-03 23:35:55.090    39
671  14.59        14.590  1813.0         1825.2 2021-10-03 23:50:55.090    39

[672 rows x 6 columns]

In [21]:
#Función adaptada a datos suavizados
def difT_CO2_cc_por_semanas(DataframeCruce, DataframeExterior, DataframeHall, PolicromosSemanas):
    """
    Atributos:
    1) DataframeCruce: Lista de dataframes por semanas correspondiente a los datos de un mes de Cruce
    2) DataframeExterior: Lista de dataframes por semanas correspondiente a los datos de un mes de Exterior
    3) DataframeHall: Lista de dataframes por semanas correspondiente a los datos de un mes de Hall
    4) DatosPolicromos: Lista de dataframes por semanas correspondiente a los datos de un mes de Policromos
    
    Devuelve:
    Una lista de listas, r. Cada elemento de r, r[i] con i=0, 1, 2, 3, 4, es una lista con los coeficiente de correlación y p 
    valores correspondientes a una semana.  r[i] = r_difT_CO2_cruce, p_difT_CO2_cruce, r_difT_CO2_hall, p_difT_CO2_hall, 
                                                   r_difT_CO2_policromos, p_difT_CO2_policromos
    
    ¿A qué corresponde cada elemento de r[i]?
    1) r_difT_CO2_cruce: Coeficiente de correlación entre la diferencia de temperaturas de Cruce y el exterior y el CO2 del 
    Cruce
    2) p_difT_CO2_cruce: P-valor correspondiente a r_difT_CO2_cruce
    3) r_difT_CO2_hall: Coeficiente de correlación entre la diferencia de temperaturas de Cruce y el exterior y el CO2 del Hall
    4) p_difT_CO2_hall: P-valor correspondiente a r_difT_CO2_hall
    5) r_difT_CO2_policromos: Coeficiente de correlación entre la diferencia de temperaturas de Cruce y el exterior y el CO2 de 
    Policromos
    6) p_difT_CO2_policromos: P-valor correspondiente a r_Tp_Te
    """
    i=0
    r=[]
    while i<len(DataframeCruce):
       #print(i)
        DataframeCruce[i].reset_index(drop=True, inplace=True)
        DataframeExterior[i].reset_index(drop=True, inplace=True)
        DataframeHall[i].reset_index(drop=True, inplace=True)
        PolicromosSemanas[i].reset_index(drop=True, inplace=True)
        
        # Variables que me van a hacer falta: Tc, Te, Th, Tp, CO2c, CO2h, CO2p
        for index, _ in DataframeExterior[i].iterrows():#Se va fuera de indice
            if  __builtins__.sum([pd.isna(DataframeCruce[i]['Tc_suavizada'][index]),
                                  pd.isna(DataframeCruce[i]['CO2c_suavizado'][index]),
                                  pd.isna(DataframeHall[i]['Th_suavizada'][index]),
                                  pd.isna(DataframeHall[i]['CO2h_suavizado'][index]),
                                  pd.isna(PolicromosSemanas[i]['Tp_suavizada'][index]),
                                  pd.isna(PolicromosSemanas[i]["CO2_suavizado"][index]),
                                  pd.isna(DataframeExterior[i]['Te_suavizada'][index])]) > 0:
                DataframeCruce[i].drop([index], axis=0, inplace=True)
                DataframeExterior[i].drop([index], axis=0, inplace=True) 
                DataframeHall[i].drop([index], axis=0, inplace=True) 
                PolicromosSemanas[i].drop([index], axis=0, inplace=True) 
                
        #Quiero los coef entre CO2 y dif de temperaturas:
        Dif_T_cruce= DataframeExterior[i]['Te_suavizada']-DataframeCruce[i]['Tc_suavizada']
        Dif_T_Hall = DataframeExterior[i]['Te_suavizada']-DataframeHall[i]['Th_suavizada']
        Dif_T_Policromos = DataframeExterior[i]['Te_suavizada']-PolicromosSemanas[i]['Tp_suavizada']
        #Mediante scipy:
        r_difT_CO2_cruce, p_difT_CO2_cruce = stats.pearsonr(Dif_T_cruce, DataframeCruce[i]['CO2c_suavizado'])
        r_difT_CO2_hall, p_difT_CO2_hall = stats.pearsonr(Dif_T_Hall, DataframeHall[i]['CO2h_suavizado'])
        r_difT_CO2_policromos, p_difT_CO2_policromos = stats.pearsonr(Dif_T_Policromos, PolicromosSemanas[i]['CO2_suavizado'])
        rs = r_difT_CO2_cruce, p_difT_CO2_cruce, r_difT_CO2_hall, p_difT_CO2_hall, r_difT_CO2_policromos, p_difT_CO2_policromos, len(DataframeCruce[i]['CO2c_suavizado'])
        r.append(rs)
        i=i+1
    return(r)

In [22]:
cc21 = difT_CO2_cc_por_semanas(SemanaCruce21, SemanaExterior21, SemanaHall21, PolicromosSemanas_2021)
cc22 = difT_CO2_cc_por_semanas(SemanaCruce22, SemanaExterior22, SemanaHall22, PolicromosSemanas_2022)

In [23]:
s1=pd.Series([cc21[0][0], cc21[1][0],cc21[2][0],cc21[3][0],cc21[4][0],cc21[5][0],cc21[6][0],cc21[7][0],cc21[8][0],cc21[9][0],
              cc21[10][0], cc21[11][0], cc21[12][0], cc21[13][0], cc21[14][0], cc21[15][0], cc21[16][0], cc21[17][0], 
              cc22[0][0], cc22[1][0],cc22[2][0],cc22[3][0],cc22[4][0],cc22[5][0],cc22[6][0],cc22[7][0],cc21[8][0],
              cc22[9][0], cc22[10][0], cc22[11][0], cc22[12][0], cc22[13][0]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s2=pd.Series([cc21[0][1], cc21[1][1],cc21[2][1],cc21[3][1],cc21[4][1],cc21[5][1],cc21[6][1],cc21[7][1],cc21[8][1],cc21[9][1],
              cc21[10][1], cc21[11][1], cc21[12][1], cc21[13][1], cc21[14][1], cc21[15][1], cc21[16][1], cc21[17][1], 
              cc22[0][1], cc22[1][1],cc22[2][1],cc22[3][1],cc22[4][1],cc22[5][1],cc22[6][1],cc22[7][1],cc21[8][1],
              cc22[9][1], cc22[10][1], cc22[11][1], cc22[12][1], cc22[13][1]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s3=pd.Series([cc21[0][2], cc21[1][2],cc21[2][2],cc21[3][2],cc21[4][2],cc21[5][2],cc21[6][2],cc21[7][2],cc21[8][2],cc21[9][2],
              cc21[10][2], cc21[11][2], cc21[12][2], cc21[13][2], cc21[14][2], cc21[15][2], cc21[16][2], cc21[17][2], 
              cc22[0][2], cc22[1][2],cc22[2][2],cc22[3][2],cc22[4][2],cc22[5][2],cc22[6][2],cc22[7][2],cc21[8][2],
              cc22[9][2], cc22[10][2], cc22[11][2], cc22[12][2], cc22[13][2]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s4=pd.Series([cc21[0][3], cc21[1][3],cc21[2][3],cc21[3][3],cc21[4][3],cc21[5][3],cc21[6][3],cc21[7][3],cc21[8][3],cc21[9][3],
              cc21[10][3], cc21[11][3], cc21[12][3], cc21[13][3], cc21[14][3], cc21[15][3], cc21[16][3], cc21[17][3], 
              cc22[0][3], cc22[1][3],cc22[2][3],cc22[3][3],cc22[4][3],cc22[5][3],cc22[6][3],cc22[7][3],cc21[8][3],
              cc22[9][3], cc22[10][3], cc22[11][3], cc22[12][3], cc22[13][3]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s5=pd.Series([cc21[0][4], cc21[1][4],cc21[2][4],cc21[3][4],cc21[4][4],cc21[5][4],cc21[6][4],cc21[7][4],cc21[8][4],cc21[9][4],
              cc21[10][4], cc21[11][4], cc21[12][4], cc21[13][4], cc21[14][4], cc21[15][4], cc21[16][4], cc21[17][4], 
              cc22[0][4], cc22[1][4],cc22[2][4],cc22[3][4],cc22[4][4],cc22[5][4],cc22[6][4],cc22[7][4],cc21[8][4],
              cc22[9][4], cc22[10][4], cc22[11][4], cc22[12][4], cc22[13][4]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s6=pd.Series([cc21[0][5], cc21[1][5],cc21[2][5],cc21[3][5],cc21[4][5],cc21[5][5],cc21[6][5],cc21[7][5],cc21[8][5],cc21[9][5],
              cc21[10][5], cc21[11][5], cc21[12][5], cc21[13][5], cc21[14][5], cc21[15][5], cc21[16][5], cc21[17][5], 
              cc22[0][5], cc22[1][5],cc22[2][5],cc22[3][5],cc22[4][5],cc22[5][5],cc22[6][5],cc22[7][5],cc21[8][5],
              cc22[9][5], cc22[10][5], cc22[11][5], cc22[12][5], cc22[13][5]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s7=pd.Series([cc21[0][6], cc21[1][6],cc21[2][6],cc21[3][6],cc21[4][6],cc21[5][6],cc21[6][6],cc21[7][6],cc21[8][6],cc21[9][6],
              cc21[10][6], cc21[11][6], cc21[12][6], cc21[13][6], cc21[14][6], cc21[15][6], cc21[16][6], cc21[17][6], 
              cc22[0][6], cc22[1][6],cc22[2][6],cc22[3][6],cc22[4][6],cc22[5][6],cc22[6][6],cc22[7][6],cc21[8][6],
              cc22[9][6], cc22[10][6], cc22[11][6], cc22[12][6], cc22[13][6]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
#unir en dataframe
CoefCorrel = pd.concat([s1, s2, s3, s4, s5, s6, s7], axis = 1)
CoefCorrel.columns = ['CC_difT_CO2_cruce', 'pvalue_difT_CO2_cruce', 'CC_difT_CO2_hall',  'pvalue_hall', 
                      'CC_difT_CO2_policromos',  'pvalue_polimos', 'nº datos']
display(CoefCorrel)
CoefCorrel.describe()

CC_difT_CO2_cruce  pvalue_difT_CO2_cruce  CC_difT_CO2_hall  \
Sem0 2021           -0.683940           1.400426e-53         -0.395945   
Sem1 2021           -0.675539           4.496192e-90         -0.467244   
Sem2 2021           -0.651230           2.456403e-82         -0.327164   
Sem3 2021           -0.558351           2.422426e-56         -0.136756   
Sem4 2021           -0.667506           3.130490e-87         -0.491607   
Sem5 2021           -0.642507           1.658126e-79         -0.287075   
Sem6 2021           -0.706036          9.657220e-102         -0.166354   
Sem7 2021           -0.605524           1.794748e-68         -0.136353   
Sem8 2021           -0.562678           2.774997e-28         -0.244686   
Sem9 2021           -0.934863           4.574907e-09         -0.722943   
Sem10 2021          -0.428352           1.064365e-30          0.580230   
Sem11 2021          -0.544230           1.078376e-52         -0.141832   
Sem12 2021          -0.584137           1.520187e-62         -0.476445   
Sem13 2021          -0.296450           5.879078e-15         -0.282523   
Sem14 2021          -0.247996           7.081364e-11         -0.193394   
Sem15 2021          -0.515469           6.930513e-47         -0.527381   
Sem0162021          -0.642053           2.313799e-79         -0.783705   
Sem17 2021          -0.523151           1.757254e-48         -0.496123   
Sem0 2022           -0.505139           1.144293e-19         -0.484493   
Sem1 2022           -0.515105           8.231118e-47         -0.181682   
Sem2 2022           -0.503238           1.991074e-44          0.285107   
Sem3 2022           -0.403736           9.816539e-28         -0.178536   
Sem4 2022           -0.487121           3.694442e-41         -0.397993   
Sem5 2022           -0.208722           5.314597e-08          0.114533   
Sem6 2022           -0.349450           1.460622e-08          0.436511   
Sem7 2022           -0.494024           6.995815e-32         -0.484662   
Sem8 2021           -0.562678           2.774997e-28         -0.244686   
Sem9 2022           -0.534767           1.319011e-50          0.153039   
Sem10 2022          -0.360283           5.007519e-22          0.264142   
Sem11 2022          -0.410971           9.039779e-29         -0.017300   
Sem12 2022          -0.378934           5.260026e-21         -0.431084   
Sem13 2022          -0.445863           8.018498e-25         -0.620210   

              pvalue_hall  CC_difT_CO2_policromos  pvalue_polimos  nº datos  
Sem0 2021    1.123222e-15               -0.409520    9.285915e-17       379  
Sem1 2021    1.783356e-37               -0.150675    9.367363e-05       667  
Sem2 2021    3.148010e-18               -0.056011    1.469421e-01       672  
Sem3 2021    3.776415e-04                0.274725    4.218461e-13       672  
Sem4 2021    7.049169e-42               -0.252900    3.420074e-11       667  
Sem5 2021    3.241997e-14                0.078528    4.184730e-02       672  
Sem6 2021    1.571751e-05               -0.236557    6.172559e-10       667  
Sem7 2021    3.931074e-04                0.158890    3.510376e-05       672  
Sem8 2021    8.939706e-06                0.300967    3.631675e-08       322  
Sem9 2021    4.702964e-04                0.799677    3.973367e-05        19  
Sem10 2021   2.217697e-60                0.257028    2.258030e-11       657  
Sem11 2021   2.381181e-04               -0.123762    1.361759e-03       667  
Sem12 2021   2.891665e-39               -0.105496    6.271652e-03       670  
Sem13 2021   1.139320e-13                0.216088    1.817501e-08       665  
Sem14 2021   4.377178e-07                0.114710    2.901975e-03       672  
Sem15 2021   2.231738e-49                0.006960    8.570792e-01       672  
Sem0162021  1.066976e-140               -0.193646    4.226177e-07       672  
Sem17 2021   4.830491e-43                0.079122    4.031731e-02       672  
Sem0 2022    5.267401e-18               -0.050102    4.019453e-01       282  
Sem1 2022

CC_difT_CO2_cruce  pvalue_difT_CO2_cruce  CC_difT_CO2_hall  \
count          32.000000           3.200000e+01         32.000000   
mean           -0.519689           2.262435e-09         -0.233894   
std             0.148213           9.663658e-09          0.323503   
min            -0.934863          9.657220e-102         -0.783705   
25%            -0.614656           1.816820e-56         -0.478457   
50%            -0.519310           1.848216e-41         -0.263605   
75%            -0.424007           1.257894e-22         -0.136655   
max            -0.208722           5.314597e-08          0.580230   

         pvalue_hall  CC_difT_CO2_policromos  pvalue_polimos    nº datos  
count   3.200000e+01               32.000000    3.200000e+01   32.000000  
mean    2.059478e-02                0.042261    5.139888e-02  578.781250  
std     1.156553e-01                0.255947    1.654225e-01  169.276779  
min    1.066976e-140               -0.409520    1.278448e-19   19.000000  
25%     1.048368e-30               -0.153406    5.097485e-10  553.750000  
50%     8.157555e-14                0.076008    1.942778e-05  667.000000  
75%     1.063416e-05                0.224868    6.449484e-03  672.000000  
max     6.543875e-01                0.799677    8.570792e-01  672.000000

In [24]:
ordenar_valores_cc (CoefCorrel, 'CC_difT_CO2_cruce', 'pvalue_difT_CO2_cruce', 'CC_difT_CO2_hall',  'pvalue_hall', 
                      'CC_difT_CO2_policromos',  'pvalue_polimos')

CC_difT_CO2_cruce  CC_difT_CO2_hall  CC_difT_CO2_policromos
cc>0.5                   0                 1                       1
cc>0                     0                 5                      17
cc>-0.5                 12                22                      14
cc>-1                   20                 4                       0
total                   32                32                      32